"""add_line_item_notes

Revision ID: 892f08211f6b
Revises: 
Create Date: 2026-01-27 16:21:25.446311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892f08211f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
